blank_issues_enabled: false
contact_links:
  - name: Milestone Report Guide
    url: https://www.notion.so/PL-EngRes-Public-b5086aea86ed4f81bc7d0721c6935e1e
    about: Please use this guide to add a milestone report.
  - name: Roadmap Report Guide
    url: https://www.notion.so/PL-EngRes-Public-b5086aea86ed4f81bc7d0721c6935e1e
    about: Please use this guide to create a roadmap for your team.
  - name: PLN Roadmap Support
    url: https://www.notion.so/PL-EngRes-Public-b5086aea86ed4f81bc7d0721c6935e1e
    about: Please ask and answer questions here.
