name: Milestone Report
description: Add a milestone to the leadership roadmap report
title: "[Milestone]: "
labels: ["Milestone"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this milestone report!
  - type: input
    id: description
    attributes:
      label: Milestone Description
      description: Give this milestone a brief description.
      placeholder: ex. Developers will be able to deploy custom smart contracts written in Rust.
    validations:
      required: true
  - type: textarea
    id: milestone-dependencies
    attributes:
      label: What issues or pull requests are needed for this milestone to be considered done?
      description: Please link all issues or pull requests that this milestone depends on to be complete.
      placeholder: "- [ ] https://github.com/PLN-Roadmap/roadmap-test/issues/1"
      value:  "- [ ] https://github.com/PLN-Roadmap/roadmap-test/issues/1"
    validations:
      required: true
  - type: dropdown
    id: target-date
    attributes:
      label: Target Date
      description: What's the expected target date for this milestone to be delivered?
      options:
        - Q3 2022
        - Q4 2022
        - Q1 2023
        - Q2 2023
        - Q3 2023
        - Q4 2023
        - Q1 2024
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: sh
  # - type: checkboxes
  #   id: terms
  #   attributes:
  #     label: Code of Conduct
  #     description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
  #     options:
  #       - label: I agree to follow this project's Code of Conduct
  #         required: true
