name: Milestone Report
description: Add a milestone to the roadmap report
title: "[Milestone]: "
labels: ["milestone"]
body:
  - type: markdown
    attributes:
      value: |
        *Thanks for taking the time to fill out this milestone report!*
  - type: input
    id: description
    attributes:
      label: Milestone Description
      description: Give this milestone a brief description.
      placeholder: ex. Developers will be able to deploy custom smart contracts written in Rust.
    validations:
      required: true
  - type: dropdown
    id: strategic-objective-alignment
    attributes:
      label: What are the strategic objectives this milestone aligns with?
      multiple: true
      options:
        - Hyperscale the knowledgeable + aligned developers improving the PL Stack
        - Deliver robust, accessible storage & retrieval of data across IPFS
        - Launch Network breakthroughs that unlock user-defined programmability in Filecoin, scalability, & decentralized compute over data
        - Keep critical team + network systems running smoothly
  - type: textarea
    id: milestone-dependencies
    attributes:
      label: What issues or pull requests are needed for this milestone to be considered done?
      description: Please link all issues or pull requests that this milestone depends on to be complete.
      placeholder: "- [ ] https://github.com/PLN-Roadmap/roadmap-test/issues/1"
      value:  "- [ ] https://github.com/PLN-Roadmap/roadmap-test/issues/1"
    validations:
      required: true
  - type: dropdown
    id: target-date
    attributes:
      label: What's the target date for this milestone to be delivered?
      description: Please select the quarter this milestone is expected to be complete.
      options:
        - Q4 2022
        - Q1 2023
        - Q2 2023
        - Q3 2023
        - Q4 2023
    validations:
      required: true
  # - type: textarea
  #   id: risks-and-mitigations
  #   attributes:
  #     label: What are the expected risks and mitigations?
  #     description: Please describe any expected risks and how you plan to mitigate them.
  #     render: sh
  # - type: checkboxes
  #   id: terms
  #   attributes:
  #     label: Code of Conduct
  #     description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
  #     options:
  #       - label: I agree to follow this project's Code of Conduct
  #         required: true
